/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyHenagonRouteImport } from './routes/why-henagon'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OurApproachRouteImport } from './routes/our-approach'
import { Route as DeliveringValueRouteImport } from './routes/delivering-value'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessPortfolioRouteImport } from './routes/business-portfolio'
import { Route as AiStackRouteImport } from './routes/ai-stack'
import { Route as AdvisoryBoardRouteImport } from './routes/advisory-board'
import { Route as AdvantageRouteImport } from './routes/advantage'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhyHenagonRoute = WhyHenagonRouteImport.update({
  id: '/why-henagon',
  path: '/why-henagon',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OurApproachRoute = OurApproachRouteImport.update({
  id: '/our-approach',
  path: '/our-approach',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveringValueRoute = DeliveringValueRouteImport.update({
  id: '/delivering-value',
  path: '/delivering-value',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPortfolioRoute = BusinessPortfolioRouteImport.update({
  id: '/business-portfolio',
  path: '/business-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStackRoute = AiStackRouteImport.update({
  id: '/ai-stack',
  path: '/ai-stack',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryBoardRoute = AdvisoryBoardRouteImport.update({
  id: '/advisory-board',
  path: '/advisory-board',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvantageRoute = AdvantageRouteImport.update({
  id: '/advantage',
  path: '/advantage',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/advantage': typeof AdvantageRoute
  '/advisory-board': typeof AdvisoryBoardRoute
  '/ai-stack': typeof AiStackRoute
  '/business-portfolio': typeof BusinessPortfolioRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/delivering-value': typeof DeliveringValueRoute
  '/our-approach': typeof OurApproachRoute
  '/services': typeof ServicesRoute
  '/why-henagon': typeof WhyHenagonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/advantage': typeof AdvantageRoute
  '/advisory-board': typeof AdvisoryBoardRoute
  '/ai-stack': typeof AiStackRoute
  '/business-portfolio': typeof BusinessPortfolioRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/delivering-value': typeof DeliveringValueRoute
  '/our-approach': typeof OurApproachRoute
  '/services': typeof ServicesRoute
  '/why-henagon': typeof WhyHenagonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/advantage': typeof AdvantageRoute
  '/advisory-board': typeof AdvisoryBoardRoute
  '/ai-stack': typeof AiStackRoute
  '/business-portfolio': typeof BusinessPortfolioRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/delivering-value': typeof DeliveringValueRoute
  '/our-approach': typeof OurApproachRoute
  '/services': typeof ServicesRoute
  '/why-henagon': typeof WhyHenagonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-us'
    | '/advantage'
    | '/advisory-board'
    | '/ai-stack'
    | '/business-portfolio'
    | '/contact'
    | '/contact-us'
    | '/delivering-value'
    | '/our-approach'
    | '/services'
    | '/why-henagon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-us'
    | '/advantage'
    | '/advisory-board'
    | '/ai-stack'
    | '/business-portfolio'
    | '/contact'
    | '/contact-us'
    | '/delivering-value'
    | '/our-approach'
    | '/services'
    | '/why-henagon'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-us'
    | '/advantage'
    | '/advisory-board'
    | '/ai-stack'
    | '/business-portfolio'
    | '/contact'
    | '/contact-us'
    | '/delivering-value'
    | '/our-approach'
    | '/services'
    | '/why-henagon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutUsRoute: typeof AboutUsRoute
  AdvantageRoute: typeof AdvantageRoute
  AdvisoryBoardRoute: typeof AdvisoryBoardRoute
  AiStackRoute: typeof AiStackRoute
  BusinessPortfolioRoute: typeof BusinessPortfolioRoute
  ContactRoute: typeof ContactRoute
  ContactUsRoute: typeof ContactUsRoute
  DeliveringValueRoute: typeof DeliveringValueRoute
  OurApproachRoute: typeof OurApproachRoute
  ServicesRoute: typeof ServicesRoute
  WhyHenagonRoute: typeof WhyHenagonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-henagon': {
      id: '/why-henagon'
      path: '/why-henagon'
      fullPath: '/why-henagon'
      preLoaderRoute: typeof WhyHenagonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-approach': {
      id: '/our-approach'
      path: '/our-approach'
      fullPath: '/our-approach'
      preLoaderRoute: typeof OurApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivering-value': {
      id: '/delivering-value'
      path: '/delivering-value'
      fullPath: '/delivering-value'
      preLoaderRoute: typeof DeliveringValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-portfolio': {
      id: '/business-portfolio'
      path: '/business-portfolio'
      fullPath: '/business-portfolio'
      preLoaderRoute: typeof BusinessPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-stack': {
      id: '/ai-stack'
      path: '/ai-stack'
      fullPath: '/ai-stack'
      preLoaderRoute: typeof AiStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory-board': {
      id: '/advisory-board'
      path: '/advisory-board'
      fullPath: '/advisory-board'
      preLoaderRoute: typeof AdvisoryBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advantage': {
      id: '/advantage'
      path: '/advantage'
      fullPath: '/advantage'
      preLoaderRoute: typeof AdvantageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutUsRoute: AboutUsRoute,
  AdvantageRoute: AdvantageRoute,
  AdvisoryBoardRoute: AdvisoryBoardRoute,
  AiStackRoute: AiStackRoute,
  BusinessPortfolioRoute: BusinessPortfolioRoute,
  ContactRoute: ContactRoute,
  ContactUsRoute: ContactUsRoute,
  DeliveringValueRoute: DeliveringValueRoute,
  OurApproachRoute: OurApproachRoute,
  ServicesRoute: ServicesRoute,
  WhyHenagonRoute: WhyHenagonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
